---
- name: Install and Configure OpenLDAP
  hosts: all
  become: true

  vars:
    ldap_domain: "example.local"
    ldap_base_dn: "dc=example,dc=local"
    ldap_admin_password: "admin123"
    ldap_organization: "Example Organization"

  tasks:
    - name: Install OpenLDAP packages
      apt:
        name: [slapd, ldap-utils, python3-ldap]
        state: present
        update_cache: yes

    - name: Configure Admin Password
      shell: |
        echo "dn: olcDatabase={1}mdb,cn=config
        changetype: modify
        replace: olcSuffix
        olcSuffix: {{ ldap_base_dn }}
        -
        replace: olcRootDN
        olcRootDN: cn=admin,{{ ldap_base_dn }}
        -
        replace: olcRootPW
        olcRootPW: {{ ldap_admin_password }}" | ldapmodify -Y EXTERNAL -H ldapi:///

    - name: Create Domain & Organization
      community.general.ldap_entry:
        dn: "{{ ldap_base_dn }}"
        objectClass: [top, dcObject, organization]
        attributes:
          dc: "{{ ldap_domain.split('.')[0] }}"
          o: "{{ ldap_organization }}"
        server_uri: ldapi:///
        bind_dn: "cn=admin,{{ ldap_base_dn }}"
        bind_pw: "{{ ldap_admin_password }}"

    - name: Add Groups
      community.general.ldap_entry:
        dn: "cn={{ item }},{{ ldap_base_dn }}"
        objectClass: [posixGroup]
        server_uri: ldapi:///
        attributes:
          gidNumber: "{{ 2000 + idx }}"
        bind_dn: "cn=admin,{{ ldap_base_dn }}"
        bind_pw: "{{ ldap_admin_password }}"
      loop: [dev, ops]
      loop_control:
        index_var: idx

    - name: Add Users
      community.general.ldap_entry:
        dn: "uid={{ item }},{{ ldap_base_dn }}"
        objectClass: [inetOrgPerson, posixAccount]
        server_uri: ldapi:///
        attributes:
          sn: "{{ item }}"
          cn: "{{ item }}"
          uidNumber: "{{ 1000 + idx }}"
          gidNumber: 2000
          homeDirectory: "/home/{{ item }}"
        bind_dn: "cn=admin,{{ ldap_base_dn }}"
        bind_pw: "{{ ldap_admin_password }}"
      loop: [user1, user2]
      loop_control:
        index_var: idx
